# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
    solutionFile: .\windows\ReactNew.sln
    manifestPath: .\windows\ReactNew\Package.appxmanifest
    packageFolderPath: .\windows\AppPackages\

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
          
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@2008f912f56e61277eefaac6d1888b750582aa16
    
    - name: Use Nerdbank.GitVersioning to set version variables
      uses: aarnott/nbgv@v0.3
      with:
        setAllVars: true
    
    - name: Tagging
      run: | 
         git config --global user.email "matteo.pagani@microsoft.com"
         git config --global user.name "Matteo Pagani"
         git tag -a ${{env.NBGV_SimpleVersion}} -m "Version ${{env.NBGV_SimpleVersion}}"
          
    
    - name: Update manifest version
      run: |
        [xml]$manifest = get-content ${{env.manifestPath}}
        $manifest.Package.Identity.Version = "${{env.NBGV_SimpleVersion}}.0"
        $manifest.save("${{env.manifestPath}}")
        
    - name: Restore Node packages
      run: yarn install
    
    - name: Restore NuGet Packages
      run: nuget restore $env:solutionFile
        
    - name: Build
      run: msbuild $env:solutionFile /p:Configuration=$env:configuration /p:AppxBundlePlatforms=$env:platform /p:AppxBundle=Never /p:UapAppxPackageBuildMode=$env:package_build_mode /p:AppxPackageSigningEnabled=false
      env:
        configuration: Release
        platform: x86
        package_build_mode: SideloadOnly
        
    - name: Install AzureSignTool
      run: dotnet tool install --global AzureSignTool --version 2.0.17
    
    - name: Sign package
      run: |
            Get-ChildItem -recurse -Include *.msix | ForEach-Object {
            $msixPath = $_.FullName
            & AzureSignTool sign -kvu ${{ secrets.AZUREKEYVAULTURL }} -kvi "${{ secrets.AZUREKEYVAULTCLIENTID }}" -kvs "${{ secrets.AZUREKEYVAULTSECRET }}" -kvc ${{ secrets.AZUREKEYVAULTCERTIFICATENAME}} -tr http://timestamp.digicert.com -v $msixPath
            }  

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: MSIX
        # Directory containing files to upload
        path: ${{env.packageFolderPath}}
      
    - name: Create a Release
      uses: actions/create-release@v1.1.1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      with:
        # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
        tag_name: v${{env.NBGV_SimpleVersion}}
        # The name of the release. For example, `Release v1.0.1`
        release_name: Release ${{env.NBGV_SimpleVersion}}
        # Text describing the contents of the tag.
      
    - name: Upload a Release Asset
      uses: actions/upload-release-asset@v1.0.2
      with:
        # The URL for uploading assets to the release
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        # The path to the asset you want to upload
        asset_path: ${{env.packageFolderPath}}\ReactNew\ReactNew_${{env.NBGV_SimpleVersion}}.0_Win32_Test\ReactNew_${{env.NBGV_SimpleVersion}}.0_Win32.msix
        # The name of the asset you want to upload
        asset_name: ReactNew.msix
        # The content-type of the asset you want to upload. See the supported Media Types here: https://www.iana.org/assignments/media-types/media-types.xhtml for more information
        asset_content_type: application/msix
